### ISSUE TITLE
Process reverse

### ISSUE THREAD

**Issue by gcxxx** [brsynth/neo4jsbml#16]
Hi everyone, I am wondering to know whether there is a way to reverse the process or not?(From neo4j to sbml)

**Comment by guillaume-gricourt** [comment]
Hello, you are right it would be a good feature. I hope we will added it soon.

**Comment by gcxxx** [comment]
> Hello, you are right it would be a good feature. I hope we will added it soon.
By the way，I want to know how to get the Json file used to create Arrows object? Does the Json file a data format for sbml file? Hope for your answer,thanks

**Comment by guillaume-gricourt** [comment]
Have a look at the documentation [readthedocs](https://neo4jsbml.readthedocs.io/en/latest/usage.html).
The schema is created with [Arrows](https://arrows.app), downloaded as a JSON file and your SBML model would be formatted with XML

**Comment by guillaume-gricourt** [comment]
First stage added in [1.0.0](https://github.com/brsynth/neo4jsbml/releases/tag/1.0.0).
If you encounter some bugs, please create an issue.
